#!/bin/bash
PATH=/sbin:/usr/sbin:/bin:/usr/bin
echo "Grid Scaler sarted"

# set defaults
[ -z ${IP_ADDRESS} ] && IP_ADDRESS=10.10.10.10

java -DipAddress="${IP_ADDRESS}" \
    -cp /target/automation-grid.jar org.openqa.grid.selenium.GridLauncherV3 \
    -role hub \
    -servlets "com.rmn.qa.servlet.AutomationTestRunServlet","com.rmn.qa.servlet.StatusServlet"



#-DPOOL_MAX=1024 
#-DawsAccessKey=foo 
#-DawsSecretKey=bar 
#-DtotalNodeCount=300 
#-DipAddress="10.10.10.10" 
#-hubConfig src/main/resources/hub.static.json 
#-log grid.log 
#-jettyMaxThreads 1024


